### PR TITLE
Support connection strings

### LINKED ISSUE #54: Support connection string
There is a note [here](https://learn.microsoft.com/en-us/azure/azure-monitor/app/api-custom-events-metrics):

> On March 31, 2025, support for instrumentation key ingestion will end. Instrumentation key ingestion will continue to work, but we'll no longer provide updates or support for the feature. [Transition to connection strings](https://learn.microsoft.com/en-us/azure/azure-monitor/app/migrate-from-instrumentation-keys-to-connection-strings) to take advantage of [new capabilities](https://learn.microsoft.com/en-us/azure/azure-monitor/app/migrate-from-instrumentation-keys-to-connection-strings#new-capabilities).

Supporting connection strings shouldn't be too hard to do. As far as I can see the JS and Python exporters support it as well.

### PR DESCRIPTION
**Pull request by frigus02**
Closes #54

### CODE REVIEW

**Comment by wserr** [comment]
Hi!

Will this PR be closed any time soon, or is there any work that needs to be done? 
I would like to use this crate, but instrumentation keys will be deprecated in 2 years in application insights.

**Comment by frigus02** [comment]
Hi. I wasn't super happy with the API, but otherwise this should be good to go.

> instrumentation keys will be deprecated in 2 years in application insights

Do you know what they're going to be replaced with? This PR just parses the instrumentation key out of the connection string. If instrumentation keys will go away entirely, this would require more work.

**Comment by wserr** [comment]
Thank you for the quick response! 

This is what I found on microsoft docs regarding the instrumentation key ingestion:

[InstrumentationKey=b380a8e3-22fb-49e2-9de6-ee3b9dd48a2e;IngestionEndpoint=https://westeurope-5.in.applicationinsights.azure.com/;LiveEndpoint=https://westeurope.livediagnostics.monitor.azure.com/](https://learn.microsoft.com/en-us/azure/azure-monitor/app/sdk-connection-string?tabs=dotnet5#overview)

So application insights will actually keep supporting it, but connectionstrings will be preferred over instrumentation keys, and with the use of connectionstrings, some new capabilities  can be unlocked (e.g. adding authorization):

https://learn.microsoft.com/en-us/azure/azure-monitor/app/migrate-from-instrumentation-keys-to-connection-strings#new-capabilities

Could these new capabilities be of any interest for your project?

**Comment by frigus02** [comment]
Thanks. Yeah, connection strings are certainly useful. As far as I can see the new capabilities boil down to:

- Being able to configure the ingestion endpoint. That's already possible with this library. But using a connection string for it makes this easier because you can copy-paste the entire connection string.
- Azure AD authentication. The docs don't looks like a connection string is strictly required here. But either way, that needs additional work.

Still, I would like to merge and release this PR. I don't expect to do it this week. But I'll try to do it end of next week.

**Comment by wserr** [comment]
That would be great! Thanks a lot :)

**Pull request merged**
