### PR TITLE
chore(deps): Update to OpenTelemetry 0.14

### PR DESCRIPTION
**Pull request by notheotherben**
This PR updates to the latest version of OpenTelemetry and makes some changes necessary to support that. I feel like there may be room to improve the `Resource.merge` method usage when we're dealing with `Option<Arc<Resource>>` types, but this seems to work fine without any bigger changes.

### CODE REVIEW

**Comment by frigus02** [comment]
Thanks @notheotherben, I completely missed that update. Look good 👍

**Comment by frigus02** [comment]
Looks like `cargo fmt` and `cargo clippy` have something to complain about. Minor stuff, though. I'm going to merge and release a new version.

**Comment by notheotherben** [comment]
Sorry about that, I should have checked to see if there was a coding standard/check to enforce that. Appreciate the merge + release.

**Comment by frigus02** [comment]
No worries. I just pushed version 0.15.0. Thanks for your help 🙂

**Pull request merged**
